name: go-dqlite-build-and-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Setup dependencies
      run: |
        sudo add-apt-repository -y ppa:dqlite/master
        sudo apt update
        sudo apt install -y golint libsqlite3-dev libuv1-dev liblz4-dev libraft-dev libdqlite-dev
        go get github.com/tsenart/deadcode
        go get github.com/go-playground/overalls

    - name: Build & Test
      run: |
        go get -t -tags libsqlite3 ./...
        go vet -tags libsqlite3 ./...
        golint
        deadcode
        export GO_DQLITE_MULTITHREAD=1
        overalls -project ${{ github.workspace }} -covermode=count -- -tags libsqlite3 -timeout 240s
        VERBOSE=1 ./test/dqlite-demo.sh
        VERBOSE=1 ./test/roles.sh

    - name: Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: overalls.coverprofile
